apiVersion: v1
kind: Pod
metadata:
  name: busybox-pid
spec:
  hostPID: true
  containers:
  - name: busybox
    image: busybox
    command: [ "sleep", "3600" ]  # Keeps the container running for an hour
    resources:
      limits:
        cpu: "100m"
        memory: "128Mi"

